version: '3.1'
services:
  app:
    container_name: note-service-0.0.1
    image: note-service-0.0.1
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgres
  dbpostgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres